name: ci
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: gradle check
        run: ./gradlew check
      - name: Save test output
        uses: actions/upload-artifact@master
        if: failure()
        with:
          name: test-result
          path: build/reports/tests/test
      - name: Save coverage output
        uses: actions/upload-artifact@master
        with:
          name: test-coverage
          path: build/reports/jacoco/test/html