name: deploy-sonatype-snapshot
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 12
        uses: actions/setup-java@v1
        with:
          java-version: 12
      - name: assembleDist
        run: ./gradlew distZip distTar
      - name: google-play-cli.tar
        uses: actions/upload-artifact@master
        with:
          name: google-play-cli.tar
          path: build/distributions/google-play-cli.tar
      - name: google-play-cli.zip
        uses: actions/upload-artifact@master
        with:
          name: google-play-cli.zip
          path: build/distributions/google-play-cli.zip
